name: tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Django ${{ matrix.django }} / Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
        django: ["4.2.*", "5.0.*", "5.1.*", "5.2.*"]
        exclude:
          # Django 4.2 doesn't support Python 3.13
          - python: "3.13"
            django: "4.2.*"
          # Django 5.0 doesn't support Python 3.13
          - python: "3.13"
            django: "5.0.*"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install --upgrade "Django==${{ matrix.django }}"
          if [ -f setup.py ] || [ -f pyproject.toml ]; then
            pip install -e .
          fi

      - name: Run tests
        working-directory: tests
        env:
          VCR_RECORD_MODE: none
        run: |
          if [[ "${{ matrix.python }}" == "3.13" && "${{ matrix.django }}" == "5.2.*" ]]; then
            coverage run --source='.,yesglot' manage.py test
            coverage report -m
            coverage xml
          else
            python manage.py test
          fi

      - name: Upload coverage to Codecov
        if: matrix.python == '3.13' && matrix.django == '5.2.*'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tests/coverage.xml
          flags: unittests
          name: yesglot-coverage
          fail_ci_if_error: false