name: tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Django ${{ matrix.django }} / Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
        django: ["4.2.*", "5.0.*", "5.1.*", "5.2.*"]
        exclude:
          # Django 4.2 doesn't support Python 3.13
          - python: "3.13"
            django: "4.2.*"
          # Django 5.0 doesn't support Python 3.13
          - python: "3.13"
            django: "5.0.*"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install --upgrade "Django==${{ matrix.django }}"
          # If you want to install the project itself (when it has setup.py/pyproject.toml):
          if [ -f setup.py ] || [ -f pyproject.toml ]; then
            pip install -e .
          fi

      - name: Run tests
        working-directory: tests
        env:
          VCR_RECORD_MODE: none
        run: |
          python manage.py test
